theme: jekyll-theme-minimal
kramdown:
  auto_ids: true
  parse_block_html: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_link: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"